<?php

/**
 * @file
 * Contains rotary_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rotary_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rotary_api module.
    case 'help.page.rotary_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Apis to connect mobile and registration form') . '</p>';
      return $output;

    default:
  }
}
