<?php

/**
 * @file
 * Contains rotary_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rotary_api_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the rotary_api module.
        case 'help.page.rotary_api':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Apis to connect mobile and registration form') . '</p>';
            return $output;

        default:
    }
}

function rotary_api_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{

    // Restrict default user edit for members, trainers, etc
    if ($form_id == "user_form") {
        $user_roles = \Drupal::currentUser()->getRoles();
        // \Drupal::logger('my_module')->notice(json_encode($user_roles));
        if ((in_array("registrant", $user_roles))) {
            die();
        }

    }

}
